# Generated by Django 3.2.3 on 2021-05-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxygen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oxygen',
            name='Address',
            field=models.TextField(default='No location'),
        ),
    ]
