# Generated by Django 3.2.3 on 2021-05-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxygen', '0003_rename_date_of_entry_oxygen_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='enter name', max_length=50),
        ),
    ]
