# Generated by Django 3.2.3 on 2021-05-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxygen', '0004_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oxygen',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
