# Generated by Django 3.2.3 on 2021-05-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxygen', '0006_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='oxygen',
            name='name',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
