# Generated by Django 3.2.3 on 2021-05-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxygen', '0007_auto_20210529_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='oxygen',
            name='additional_info',
            field=models.TextField(default=' '),
        ),
    ]
