# Generated by Django 3.2.3 on 2021-05-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxygen', '0008_oxygen_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oxygen',
            name='Address',
            field=models.TextField(blank=True, default='No location'),
        ),
        migrations.AlterField(
            model_name='oxygen',
            name='additional_info',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AlterField(
            model_name='oxygen',
            name='hospital',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
