# Generated by Django 3.2.3 on 2021-06-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxygen', '0009_auto_20210530_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oxygen',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
