# Generated by Django 3.2.3 on 2021-06-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oxygen', '0010_alter_oxygen_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oxygen',
            name='created',
        ),
    ]
