# Generated by Django 3.2.3 on 2021-06-03 07:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('oxygen', '0012_oxygen_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='oxygen',
            name='verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='oxygen',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 7, 49, 6, 447025, tzinfo=utc)),
        ),
    ]
