# Generated by Django 3.2.3 on 2021-06-04 08:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('oxygen', '0013_auto_20210603_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oxygen',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 4, 8, 6, 5, 48835, tzinfo=utc)),
        ),
    ]
