# Generated by Django 3.2.3 on 2021-06-04 16:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('oxygen', '0014_alter_oxygen_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oxygen',
            old_name='verification',
            new_name='is_verified',
        ),
        migrations.AlterField(
            model_name='oxygen',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 4, 16, 37, 10, 217316, tzinfo=utc)),
        ),
    ]
