# Generated by Django 3.2.3 on 2021-06-05 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('oxygen', '0015_auto_20210604_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oxygen',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 5, 14, 45, 9, 283877, tzinfo=utc)),
        ),
    ]
