# Generated by Django 3.2.3 on 2021-06-16 17:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('oxygen', '0016_alter_oxygen_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oxygen',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 17, 7, 51, 313450, tzinfo=utc)),
        ),
    ]
