# Generated by Django 3.2.3 on 2021-06-23 16:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('oxygen', '0018_alter_oxygen_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oxygen',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 16, 15, 56, 838233, tzinfo=utc)),
        ),
    ]
