# Generated by Django 3.2.3 on 2021-05-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=50)),
                ('city', models.CharField(max_length=200)),
                ('Address', models.TextField(default='No location')),
                ('hospital', models.CharField(max_length=200)),
                ('poc', models.CharField(max_length=200)),
                ('additional_info', models.TextField(default=' ')),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
