# Generated by Django 3.2.3 on 2021-06-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0002_auto_20210530_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
