# Generated by Django 3.2.3 on 2021-05-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='Location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
    ]
